# Generated by Django 6.0.4 on 2026-04-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=20)),
                ('simage', models.ImageField(default='Default.webp', upload_to='uploads/')),
            ],
        ),
    ]
